import { Inter } from 'next/font/google'
import './globals.css'


const inter = Inter({ subsets: ['latin'] })
export const metadata = {
  title: 'UPI ScanMate',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
        <head>
          <link rel="manifest" href="/manifest.json" />
          <link rel="apple-touch-icon" href="/icon.png"></link>
          <meta name="theme-color" content="#fff" />
          <link rel="icon" type="image/x-icon" href="/favicon.ico"/>
        </head>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
